### PR TITLE
This implementation is based on the internal Capistrano::Git strategy.

### PR DESCRIPTION
**Pull request by carld**
It clones the repository locally before archiving to a tarfile
and then uploading it to the remote host servers.

### CODE REVIEW

**Comment by xuwupeng2000** [comment]
:100:

**Comment by Daniel-ltw** [comment]
Finished in 0.01355 seconds (files took 0.25738 seconds to load)
10 examples, 2 failures

Failed examples:

rspec ./spec/lib/capistrano/gitcopy_spec.rb:91 # Capistrano::GitCopy::DefaultStrategy#release should run git archive with a subtree
rspec ./spec/lib/capistrano/gitcopy_spec.rb:79 # Capistrano::GitCopy::DefaultStrategy#release should run git archive without a subtree

Is this just me?

**Comment by xuwupeng2000** [comment]
Can we fix this ? Then I will make another official release ?

**Comment by Daniel-ltw** [comment]
Looks to me, it might be missing the :tmp_dir param, :application params and the :current_revision params, might need to specify those in the test?

**Pull request merged**
